# Generated by Django 2.0.1 on 2018-01-14 21:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mobilesapi', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mobilephone',
            old_name='color',
            new_name='colour',
        ),
    ]
